---
# handlers file for conesphere.mail.inbound
- name: restart_smtpd
  service:
    name: smtpd
    enabled: yes
    state: restarted
- name: restart_spamd
  shell: |
    rcctl enable spamd
    rcctl restart spamd
- name: restart_greyscanner
  service:
    name: greyscanner
    enabled: yes
    state: restarted
- name: reload_pfctl
  shell: pfctl -f /etc/pf.conf
